name: context demo
on: workflow_dispatch
jobs:
    context:
        runs-on: ubuntu-latest
        steps:
            - name: use context variable
              run: |
                echo "this workflow trigered by ${{github.actor}}\n"
                echo "repo name is ${{github.repository}}"