name: if-demo
on:     
    push:
        branches: 
            - main
            - develop
jobs:
    prod-check:
        runs-on: ubuntu-latest
        steps:
            - name: check for actor
              if: ${{github.actor == 'rahulgihub8279'}}
              run: echo "triggered by ${{github.actor}} & repo is ${{github.repository}}"
            - name: default check 
              run: echo "runing default"


