name: input demo
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: choose the env to deploy
                required: true 

jobs:
    input-demo:
        runs-on: ubuntu-latest
        steps:
            - name: delpoy app
              run: echo "deploying the app to ${{inputs.environment}}"
              
